# 第一题

## 代码

```go
package main

import "fmt"

func deferCall() {
	defer func() {fmt.Println("打印前")}()
	defer func() {fmt.Println("打印中")}()
	defer func() {fmt.Println("打印后")}()
	panic("触发异常")
}

func main() {
	deferCall()
}
```

## 输出

```go
打印后
打印中
打印前
panic: 触发异常

goroutine 1 [running]:
main.deferCall()
        /Users/sliverhorn/Go/src/github.com/SliverHorn/Interview/questions/1.go:9 +0x7e
main.main()
        /Users/sliverhorn/Go/src/github.com/SliverHorn/Interview/questions/1.go:13 +0x20

```

## 参考解析

- defer的执行顺序是后进先出
- 当出现panic语句的时候,会先按照defer的后进先出的顺序执行,最后才执行panic